image: alpine/edge
packages:
  - eudev-dev
  - libinput-dev
  - libseat-dev
  - mesa-dev
  - libffi-dev
  - expat-dev
  - hwdata-dev
  - libdisplay-info-dev
  - libxkbcommon-dev
  - xcb-util-image-dev
  - xcb-util-renderutil-dev
  - xcb-util-wm-dev
  - pixman-dev
  - libevdev-dev
  - wayland-protocols
  - meson
  - scdoc
  - tar
  - wget
  - xz
  - hwdata
sources:
  - https://gitlab.freedesktop.org/wayland/wayland.git
  - https://gitlab.freedesktop.org/wlroots/wlroots.git
  - https://codeberg.org/river/river.git
  - https://git.sr.ht/~novakane/rivercarro
tasks:
  - install_deps: |
      cd wayland
      git checkout 1.23.1
      meson setup build -Ddocumentation=false -Dtests=false --prefix /usr
      sudo ninja -C build install
      cd ..

      cd wlroots
      git checkout 0.17.4
      meson setup build --auto-features=enabled -Drenderers=gles2 -Dexamples=false \
            -Dwerror=false -Db_ndebug=false -Dxwayland=disabled -Dxcb-errors=disabled --prefix /usr
      sudo ninja -C build/ install
      cd ..

      wget -nv https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
      # Remove a lot of useless lines from tar output.
      tar -xvf zig-linux-x86_64-0.14.0.tar.xz 1>/dev/null
      sudo mv zig-linux-x86_64-0.14.0/zig /usr/bin/
      sudo mv zig-linux-x86_64-0.14.0/lib /usr/lib/zig

      cd river
      sudo zig build --prefix /usr
  - build: |
      cd rivercarro
      zig build
  - format: |
      cd rivercarro
      zig fmt --check src/
      zig fmt --check build.zig
      zig fmt --check build.zig.zon
